# Form implementation generated from reading ui file 'C:\Users\bicht\PycharmProjects\PythonProject1\giaodiendangnhap.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1029, 748)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(270, 240, 101, 20))
        self.label_2.setObjectName("label_2")
        self.password = QtWidgets.QLineEdit(parent=Form)
        self.password.setGeometry(QtCore.QRect(380, 220, 311, 61))
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(270, 170, 101, 20))
        self.label.setObjectName("label")
        self.user_name = QtWidgets.QLineEdit(parent=Form)
        self.user_name.setGeometry(QtCore.QRect(380, 150, 311, 61))
        self.user_name.setObjectName("user_name")
        self.btn_dn = QtWidgets.QPushButton(parent=Form)
        self.btn_dn.setGeometry(QtCore.QRect(440, 300, 191, 51))
        self.btn_dn.setObjectName("btn_dn")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(450, 360, 171, 20))
        self.label_3.setObjectName("label_3")
        self.btn_dk = QtWidgets.QPushButton(parent=Form)
        self.btn_dk.setGeometry(QtCore.QRect(440, 390, 191, 51))
        self.btn_dk.setObjectName("btn_dk")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#2ea890;\">PASSWORD</span></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#2ea890;\">USER NAME</span></p></body></html>"))
        self.btn_dn.setText(_translate("Form", "ĐĂNG NHẬP"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#2ea890;\">Chưa có tài khoản?</span></p></body></html>"))
        self.btn_dk.setText(_translate("Form", "ĐĂNG KÍ"))
