# Form implementation generated from reading ui file 'C:\Users\bicht\PycharmProjects\PythonProject1\giaodiendangki.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1448, 947)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(140, 160, 101, 20))
        self.label.setObjectName("label")
        self.user_name = QtWidgets.QLineEdit(parent=Form)
        self.user_name.setGeometry(QtCore.QRect(250, 140, 311, 61))
        self.user_name.setObjectName("user_name")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(140, 230, 101, 20))
        self.label_2.setObjectName("label_2")
        self.password = QtWidgets.QLineEdit(parent=Form)
        self.password.setGeometry(QtCore.QRect(250, 210, 311, 61))
        self.password.setObjectName("password")
        self.btn_dxu = QtWidgets.QPushButton(parent=Form)
        self.btn_dxu.setGeometry(QtCore.QRect(250, 290, 151, 41))
        self.btn_dxu.setObjectName("btn_dxu")
        self.btn_dxp = QtWidgets.QPushButton(parent=Form)
        self.btn_dxp.setGeometry(QtCore.QRect(410, 290, 151, 41))
        self.btn_dxp.setObjectName("btn_dxp")
        self.btn_dk = QtWidgets.QPushButton(parent=Form)
        self.btn_dk.setGeometry(QtCore.QRect(570, 190, 141, 41))
        self.btn_dk.setObjectName("btn_dk")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#2ea890;\">USER NAME</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#2ea890;\">PASSWORD</span></p></body></html>"))
        self.btn_dxu.setText(_translate("Form", "ĐỀ XUẤT USER NAME"))
        self.btn_dxp.setText(_translate("Form", "ĐỀ XUẤT PASSWORD"))
        self.btn_dk.setText(_translate("Form", "ĐĂNG KÍ"))
